[programs.localnet]
factory = "FyuPaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
exchange = "Fx9PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
pyth = "Fz9PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/pindaroso/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
