anchor_version = "0.17.0"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
factory = "FyuPaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
exchange = "Fx9PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
pyth = "Fz9PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[scripts]
test = "mocha -t 1000000 tests/"
